//! Source inputs for diagnostic snapshot acceptance
//!
//! Fixture names and constructed cases run in the pinned reference order.
//! Rendered output is compared with the matching diagnostic expected file.

/// Pins the OCaml inputs represented by the diagnostic cases.
pub const REVISION: &str = "960e2922b55288722c413732002e33ac06664e6f";

/// Lists file fixtures and constructed parser inputs in snapshot order.
pub const PARSE: &[&str] = &[
    "parse-hint-on-plain.watsup",
    "parse-hole-index-out-of-range.watsup",
    "parse-illegal-escape.watsup",
    "parse-relation-body-must-be-notation.watsup",
    "parse-stray-non-ascii-char.watsup",
    "parse-stray-printable.watsup",
    "parse-stray-rbrace.watsup",
    "parse-struct-no-fields.watsup",
    "parse-syntax-empty-body.watsup",
    "parse-syntax-no-ids.watsup",
    "parse-unclosed-block-comment.watsup",
    "parse-unclosed-text-literal.watsup",
    "parse-variant-bar-no-cases.watsup",
    "parse-io-error",
    "parse-illegal-control-in-text-literal",
    "parse-malformed-mixop",
    "parse-malformed-utf8",
    "parse-malformed-utf8-in-comment",
    "parse-misplaced-control-char",
    "parse-directory-io-error",
];

/// Lists elaboration fixtures in pinned reference order.
pub const ELAB: &[&str] = &[
    "ctx-builtin-dec-redefined.watsup",
    "ctx-builtin-dec-tparam-duplicate.watsup",
    "ctx-dec-redefined.watsup",
    "ctx-dec-tparam-duplicate.watsup",
    "ctx-dec-undefined.watsup",
    "ctx-defined-dec-undefined.watsup",
    "ctx-extern-dec-redefined.watsup",
    "ctx-extern-dec-tparam-duplicate.watsup",
    "ctx-extern-relation-redefined.watsup",
    "ctx-extern-relation-rules.watsup",
    "ctx-function-otherwise-redefined.watsup",
    "ctx-funparam-tparam-duplicate.watsup",
    "ctx-invalid-metavar-in-prem.watsup",
    "ctx-metavar-id-has-suffix.watsup",
    "ctx-metavar-redefined.watsup",
    "ctx-otherwise-redefined.watsup",
    "ctx-relation-redefined.watsup",
    "ctx-relation-undefined-in-premise.watsup",
    "ctx-relation-undefined.watsup",
    "ctx-rulegroup-redefined.watsup",
    "ctx-table-dec-redefined.watsup",
    "ctx-table-dec-undefined.watsup",
    "ctx-table-function-required.watsup",
    "ctx-table-rows-redefined.watsup",
    "ctx-type-already-defined-in-prem.watsup",
    "ctx-type-already-defined-in-var.watsup",
    "ctx-type-fully-redefined.watsup",
    "empty-iteration-expression.watsup",
    "empty-iteration-premise.watsup",
    "extern-type-syn-invalid-id.watsup",
    "iteration-dimension-mismatch.watsup",
    "relation-input-hint-duplicate-index.watsup",
    "relation-input-hint-empty.watsup",
    "relation-input-hint-non-hole.watsup",
    "relation-input-hint-out-of-bounds.watsup",
    "relation-iter-otherwise-premise.watsup",
    "relation-iter-var-premise.watsup",
    "relation-missing-rules.watsup",
    "relation-multiple-otherwise-premises.watsup",
    "relation-negated-premise-on-output-relation.watsup",
    "relation-no-input-hint.watsup",
    "rule-multiple-otherwise-rules.watsup",
    "rule-other-rule-before-otherwise.watsup",
    "rule-relation-mismatch.watsup",
    "table-function-parameter.watsup",
    "table-missing-rows.watsup",
    "table-non-bool-return.watsup",
    "type-call-arg-arity-mismatch.watsup",
    "type-call-targ-arity-mismatch.watsup",
    "type-clause-arg-arity-mismatch.watsup",
    "type-clause-tparam-mismatch.watsup",
    "type-dec-missing-clauses.watsup",
    "type-define-extern.watsup",
    "type-extend-extern.watsup",
    "type-extend-forward-decl.watsup",
    "type-extend-param.watsup",
    "type-extend-primitive.watsup",
    "type-extend-struct.watsup",
    "type-forward-tparam-mismatch.watsup",
    "type-funarg-expected-exp-got-fun.watsup",
    "type-funarg-expected-fun-got-exp.watsup",
    "type-funarg-name-mismatch.watsup",
    "type-funarg-signature-mismatch.watsup",
    "type-functyp-param-arity-mismatch.watsup",
    "type-functyp-tparam-arity-mismatch.watsup",
    "type-fuse-outside-hint.watsup",
    "type-hole-outside-hint.watsup",
    "type-latex-outside-hint.watsup",
    "type-missing-definition.watsup",
    "type-redeclared.watsup",
    "type-syn-invalid-id.watsup",
    "type-syn-tparam-duplicate.watsup",
    "type-typ-invalid-id.watsup",
    "type-typ-invalid-tparam.watsup",
    "type-undefined-syntax.watsup",
    "type-unparen-outside-hint.watsup",
    "type-variant-mixop-collision.watsup",
    "type-vart-targ-arity-mismatch.watsup",
];
