//! Pinned negative-case inventory and migration ownership
//!
//! Pending rows describe acceptance obligations, not passing tests.
//! Coordinates use one-based lines and zero-based byte columns.
//! Codes describe semantic checks; forwarding cases keep the originating code.

use p4spec_rust::diagnostic::Severity;

use super::Suite;

/// Pins the OCaml inputs and expectations for every row in the catalog.
pub const REVISION: &str = "960e2922b55288722c413732002e33ac06664e6f";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
/// Distinguishes executed acceptance from pending work and absent features.
pub enum State {
    Active,
    Pending,
    Deferred(&'static str),
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
/// Distinguishes rejected inputs, warnings, and boundary preservation checks.
pub enum Kind {
    Failure,
    Warning,
    Preservation,
}

/// Records a primary location with an endpoint when the reference proves it.
pub struct Location {
    pub file: &'static str,
    pub start: (usize, usize),
    pub end: Option<(usize, usize)>,
}

/// Maps one pinned reference case to its native diagnostic and migration owner.
pub struct Case {
    pub name: &'static str,
    pub suite: Suite,
    pub owner: &'static str,
    pub reference_code: Option<&'static str>,
    pub code: Option<&'static str>,
    pub severity: Severity,
    pub source: &'static str,
    pub kind: Kind,
    pub state: State,
    pub primary: Option<Location>,
    pub obligations: &'static str,
}

/// Lists all reference cases, grouped in the source suite's order.
pub const CASES: &[Case] = &[
    Case {
        name: "parse-hint-on-plain-bar-multi.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/hint-on-plain-type"),
        code: Some("parse/plain-type-hint-unsupported"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-hint-on-plain-bar-multi.watsup",
            start: (4, 19),
            end: Some((4, 29)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-hint-on-plain-bar-single.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/hint-on-plain-type"),
        code: Some("parse/plain-type-hint-unsupported"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-hint-on-plain-bar-single.watsup",
            start: (4, 19),
            end: Some((4, 29)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-hint-on-plain-no-bar-multi.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/hint-on-plain-type"),
        code: Some("parse/plain-type-hint-unsupported"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-hint-on-plain-no-bar-multi.watsup",
            start: (4, 17),
            end: Some((4, 27)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-hint-on-plain-no-bar-single.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/hint-on-plain-type"),
        code: Some("parse/plain-type-hint-unsupported"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-hint-on-plain-no-bar-single.watsup",
            start: (4, 17),
            end: Some((4, 27)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-hole-index-out-of-range.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/hole-index-out-of-range"),
        code: Some("parse/hole-index-out-of-bounds"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-hole-index-out-of-range.watsup",
            start: (6, 13),
            end: Some((6, 34)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-illegal-escape.watsup",
        suite: Suite::Parse,
        owner: "D01",
        reference_code: Some("parse/illegal-escape"),
        code: Some("parse/text-escape-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-illegal-escape.watsup",
            start: (3, 4),
            end: Some((3, 6)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-relation-body-must-be-notation.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/notation-type-expected"),
        code: Some("parse/relation-signature-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-relation-body-must-be-notation.watsup",
            start: (3, 12),
            end: Some((3, 15)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-stray-non-ascii-char.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/misplaced-unicode-char"),
        code: Some("parse/character-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-stray-non-ascii-char.watsup",
            start: (3, 0),
            end: Some((3, 2)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-stray-printable.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/unexpected-character"),
        code: Some("parse/character-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-stray-printable.watsup",
            start: (3, 0),
            end: Some((3, 1)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-stray-rbrace.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/unexpected-token"),
        code: Some("parse/token-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-stray-rbrace.watsup",
            start: (3, 0),
            end: Some((3, 1)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-struct-no-fields.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/struct-no-fields"),
        code: Some("parse/struct-field-missing"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-struct-no-fields.watsup",
            start: (3, 13),
            end: Some((3, 15)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-syntax-empty-body.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/syntax-empty-body"),
        code: Some("parse/syntax-body-missing"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-syntax-empty-body.watsup",
            start: (3, 12),
            end: Some((3, 12)),
        }),
        obligations: "Match the grammar production range, including an empty syntax body.",
    },
    Case {
        name: "parse-syntax-no-ids.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/syntax-no-ids"),
        code: Some("parse/syntax-identifier-missing"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-syntax-no-ids.watsup",
            start: (3, 0),
            end: Some((3, 6)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-unclosed-block-comment.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/unclosed-block-comment"),
        code: Some("parse/block-comment-incomplete"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-unclosed-block-comment.watsup",
            start: (4, 0),
            end: Some((4, 0)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-unclosed-text-literal.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/unclosed-text-literal"),
        code: Some("parse/text-literal-incomplete"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-unclosed-text-literal.watsup",
            start: (3, 4),
            end: Some((3, 4)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-variant-bar-no-cases.watsup",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/variant-no-cases"),
        code: Some("parse/variant-case-missing"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location {
            file: "parse-variant-bar-no-cases.watsup",
            start: (3, 13),
            end: Some((3, 14)),
        }),
        obligations: "Match the grammar production range, including an empty syntax body.",
    },
    Case {
        name: "parse-io-error",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/file-io-error"),
        code: Some("parse/file-read-failed"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location { file: "missing-input.watsup", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Preserve the file-only primary location without inventing a line.",
    },
    Case {
        name: "parse-illegal-control-in-text-literal",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/illegal-control-in-text-literal"),
        code: Some("parse/text-character-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location { file: "<string>", start: (1, 1), end: Some((1, 1)) }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-malformed-mixop",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/malformed-mixop"),
        code: Some("parse/mixfix-operator-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "parse-malformed-utf8",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/malformed-utf8"),
        code: Some("parse/source-encoding-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location { file: "<string>", start: (1, 0), end: Some((1, 1)) }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-malformed-utf8-in-comment",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/malformed-utf8-in-comment"),
        code: Some("parse/comment-encoding-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location { file: "<string>", start: (1, 2), end: Some((1, 3)) }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-misplaced-control-char",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/misplaced-control-char"),
        code: Some("parse/character-invalid"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: Some(Location { file: "<string>", start: (1, 0), end: Some((1, 1)) }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "parse-directory-io-error",
        suite: Suite::Parse,
        owner: "D02",
        reference_code: Some("parse/input-path-io-error"),
        code: Some("parse/input-path-read-failed"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Failure,
        state: State::Active,
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "ctx-builtin-dec-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/builtin-function-redefined"),
        code: Some("elab/builtin-function-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-builtin-dec-redefined.watsup",
            start: (4, 13),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-builtin-dec-redefined.watsup:3:13 (verify endpoint at source site) originally defined here",
    },
    Case {
        name: "ctx-builtin-dec-tparam-duplicate.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/builtin-dec-tparam-not-distinct"),
        code: Some("elab/builtin-function-type-parameter-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-builtin-dec-tparam-duplicate.watsup",
            start: (4, 21),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-builtin-dec-tparam-duplicate.watsup:4:18 (verify endpoint at source site) first declared here",
    },
    Case {
        name: "ctx-dec-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/function-redefined"),
        code: Some("elab/function-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-dec-redefined.watsup",
            start: (4, 5),
            end: Some((4, 7)),
        }),
        obligations: "Secondary: ctx-dec-redefined.watsup:3:5..3:7 originally defined here",
    },
    Case {
        name: "ctx-dec-tparam-duplicate.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/dec-tparam-not-distinct"),
        code: Some("elab/function-type-parameter-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-dec-tparam-duplicate.watsup",
            start: (3, 13),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-dec-tparam-duplicate.watsup:3:10 (verify endpoint at source site) first declared here",
    },
    Case {
        name: "ctx-dec-undefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/function-undefined"),
        code: Some("elab/function-undefined"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-dec-undefined.watsup",
            start: (6, 18),
            end: Some((6, 26)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-defined-dec-undefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/function-declaration-required"),
        code: Some("elab/function-declaration-missing"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-defined-dec-undefined.watsup",
            start: (3, 5),
            end: Some((3, 13)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-extern-dec-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/extern-function-redefined"),
        code: Some("elab/extern-function-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-extern-dec-redefined.watsup",
            start: (2, 12),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-extern-dec-redefined.watsup:1:12 (verify endpoint at source site) originally defined here",
    },
    Case {
        name: "ctx-extern-dec-tparam-duplicate.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/extern-dec-tparam-not-distinct"),
        code: Some("elab/extern-function-type-parameter-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-extern-dec-tparam-duplicate.watsup",
            start: (1, 20),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-extern-dec-tparam-duplicate.watsup:1:17 (verify endpoint at source site) first declared here",
    },
    Case {
        name: "ctx-extern-relation-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/extern-relation-redefined"),
        code: Some("elab/extern-relation-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-extern-relation-redefined.watsup",
            start: (5, 16),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-extern-relation-redefined.watsup:1:16 (verify endpoint at source site) originally defined here",
    },
    Case {
        name: "ctx-extern-relation-rules.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/extern-relation-rules"),
        code: Some("elab/extern-relation-rule-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-extern-relation-rules.watsup",
            start: (5, 5),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-extern-relation-rules.watsup:1:16 (verify endpoint at source site) extern relation declared here",
    },
    Case {
        name: "ctx-function-otherwise-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/function-otherwise-redefined"),
        code: Some("elab/function-otherwise-clause-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-function-otherwise-redefined.watsup",
            start: (8, 0),
            end: Some((9, 14)),
        }),
        obligations: "Secondary: ctx-function-otherwise-redefined.watsup:5:0..6:14 previous `otherwise` clause defined here",
    },
    Case {
        name: "ctx-funparam-tparam-duplicate.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/funparam-tparam-not-distinct"),
        code: Some("elab/function-parameter-type-parameter-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-funparam-tparam-duplicate.watsup",
            start: (4, 20),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-funparam-tparam-duplicate.watsup:4:17 (verify endpoint at source site) first declared here",
    },
    Case {
        name: "ctx-invalid-metavar-in-prem.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/var-prem-invalid-metavar"),
        code: Some("elab/metavariable-identifier-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-invalid-metavar-in-prem.watsup",
            start: (11, 9),
            end: Some((11, 12)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-metavar-id-has-suffix.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/var-def-invalid-metavar"),
        code: Some("elab/metavariable-identifier-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-metavar-id-has-suffix.watsup",
            start: (4, 4),
            end: Some((4, 7)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-metavar-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/meta-variable-redefined"),
        code: Some("elab/metavariable-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location { file: "ctx-metavar-redefined.watsup", start: (4, 4), end: None }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-metavar-redefined.watsup:3:4 (verify endpoint at source site) originally defined here",
    },
    Case {
        name: "ctx-otherwise-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/relation-otherwise-redefined"),
        code: Some("elab/relation-otherwise-rule-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-otherwise-redefined.watsup",
            start: (10, 0),
            end: Some((12, 14)),
        }),
        obligations: "Secondary: ctx-otherwise-redefined.watsup:6:0..8:14 previous `otherwise` rule defined here",
    },
    Case {
        name: "ctx-relation-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/relation-redefined"),
        code: Some("elab/relation-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location { file: "ctx-relation-redefined.watsup", start: (8, 9), end: None }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: ctx-relation-redefined.watsup:5:9 (verify endpoint at source site) originally defined here",
    },
    Case {
        name: "ctx-relation-undefined-in-premise.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/relation-undefined"),
        code: Some("elab/relation-undefined"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-relation-undefined-in-premise.watsup",
            start: (10, 5),
            end: Some((10, 12)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-relation-undefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/rule-relation-undefined"),
        code: Some("elab/relation-undefined"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-relation-undefined.watsup",
            start: (5, 5),
            end: Some((5, 12)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-rulegroup-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/rule-group-redefined"),
        code: Some("elab/relation-rule-group-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-rulegroup-redefined.watsup",
            start: (9, 6),
            end: Some((9, 11)),
        }),
        obligations: "Secondary: ctx-rulegroup-redefined.watsup:6:6..6:11 originally defined here",
    },
    Case {
        name: "ctx-table-dec-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-function-redefined"),
        code: Some("elab/table-function-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-table-dec-redefined.watsup",
            start: (2, 9),
            end: Some((2, 16)),
        }),
        obligations: "Secondary: ctx-table-dec-redefined.watsup:1:9..1:16 originally defined here",
    },
    Case {
        name: "ctx-table-dec-undefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-function-undefined"),
        code: Some("elab/table-function-undefined"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-table-dec-undefined.watsup",
            start: (1, 9),
            end: Some((1, 16)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "ctx-table-function-required.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-function-required"),
        code: Some("elab/table-function-kind-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-table-function-required.watsup",
            start: (3, 9),
            end: Some((3, 15)),
        }),
        obligations: "Secondary: ctx-table-function-required.watsup:1:5..1:12 function declared here",
    },
    Case {
        name: "ctx-table-rows-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-rows-redefined"),
        code: Some("elab/table-definition-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-table-rows-redefined.watsup",
            start: (6, 9),
            end: Some((6, 15)),
        }),
        obligations: "Secondary: ctx-table-rows-redefined.watsup:4:4..4:13 first table definition here",
    },
    Case {
        name: "ctx-type-already-defined-in-prem.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/var-prem-type-redefined"),
        code: Some("elab/metavariable-name-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-type-already-defined-in-prem.watsup",
            start: (11, 9),
            end: Some((11, 12)),
        }),
        obligations: "Secondary: ctx-type-already-defined-in-prem.watsup:4:7..4:10 originally defined here",
    },
    Case {
        name: "ctx-type-already-defined-in-var.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/var-def-type-redefined"),
        code: Some("elab/metavariable-name-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-type-already-defined-in-var.watsup",
            start: (6, 4),
            end: Some((6, 7)),
        }),
        obligations: "Secondary: ctx-type-already-defined-in-var.watsup:4:7..4:10 originally defined here",
    },
    Case {
        name: "ctx-type-fully-redefined.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/typ-fully-redefined"),
        code: Some("elab/type-definition-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "ctx-type-fully-redefined.watsup",
            start: (4, 7),
            end: Some((4, 10)),
        }),
        obligations: "Secondary: ctx-type-fully-redefined.watsup:3:7..3:10 originally defined here",
    },
    Case {
        name: "empty-iteration-expression.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/empty-iteration-expression"),
        code: Some("elab/expression-iteration-variable-missing"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "empty-iteration-expression.watsup",
            start: (4, 9),
            end: Some((4, 11)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "empty-iteration-premise.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/empty-iteration-premise"),
        code: Some("elab/premise-iteration-variable-missing"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "empty-iteration-premise.watsup",
            start: (10, 5),
            end: Some((10, 15)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "extern-type-syn-invalid-id.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/extern-syn-invalid-id"),
        code: Some("elab/type-identifier-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "extern-type-syn-invalid-id.watsup",
            start: (1, 14),
            end: Some((1, 17)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "iteration-dimension-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/iteration-dimension-mismatch"),
        code: Some("elab/variable-iteration-dimension-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "iteration-dimension-mismatch.watsup",
            start: (4, 13),
            end: Some((4, 16)),
        }),
        obligations: "Secondary: iteration-dimension-mismatch.watsup:4:7..4:10 other occurrence has dimension `int*`",
    },
    Case {
        name: "relation-input-hint-duplicate-index.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/relation-input-hint-duplicate-index"),
        code: Some("elab/relation-input-hint-index-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-input-hint-duplicate-index.watsup",
            start: (6, 19),
            end: Some((6, 21)),
        }),
        obligations: "Secondary: relation-input-hint-duplicate-index.watsup:6:16..6:18 first occurrence here",
    },
    Case {
        name: "relation-input-hint-empty.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/relation-input-hint-empty"),
        code: Some("elab/relation-input-hint-index-missing"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-input-hint-empty.watsup",
            start: (6, 12),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "relation-input-hint-non-hole.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/relation-input-hint-non-hole"),
        code: Some("elab/relation-input-hint-element-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-input-hint-non-hole.watsup",
            start: (7, 13),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "relation-input-hint-out-of-bounds.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/relation-input-hint-out-of-bounds"),
        code: Some("elab/relation-input-hint-index-out-of-bounds"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-input-hint-out-of-bounds.watsup",
            start: (4, 13),
            end: Some((4, 15)),
        }),
        obligations: "Secondary: relation-input-hint-out-of-bounds.watsup:3:12..3:22 relation has 2 positions",
    },
    Case {
        name: "relation-iter-otherwise-premise.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/iter-otherwise-premise"),
        code: Some("elab/otherwise-premise-iteration-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-iter-otherwise-premise.watsup",
            start: (8, 6),
            end: Some((8, 15)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "relation-iter-var-premise.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/iter-var-premise"),
        code: Some("elab/variable-premise-iteration-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-iter-var-premise.watsup",
            start: (10, 6),
            end: Some((10, 17)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "relation-missing-rules.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/relation-missing-rules"),
        code: Some("elab/relation-rule-missing"),
        severity: Severity::Warning,
        source: "elab",
        kind: Kind::Warning,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-missing-rules.watsup",
            start: (6, 0),
            end: Some((7, 16)),
        }),
        obligations: "Operation succeeds while collecting this warning; do not demand a fatal failure.",
    },
    Case {
        name: "relation-multiple-otherwise-premises.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/prem-multiple-otherwise"),
        code: Some("elab/otherwise-premise-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-multiple-otherwise-premises.watsup",
            start: (9, 5),
            end: Some((9, 14)),
        }),
        obligations: "Secondary: relation-multiple-otherwise-premises.watsup:8:5..8:14 first `otherwise` premise here",
    },
    Case {
        name: "relation-negated-premise-on-output-relation.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/negated-premise-has-outputs"),
        code: Some("elab/relation-premise-negation-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-negated-premise-on-output-relation.watsup",
            start: (16, 14),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: relation-negated-premise-on-output-relation.watsup:5:16..5:18 relation signature with output positions here",
    },
    Case {
        name: "relation-no-input-hint.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/relation-no-input-hint"),
        code: Some("elab/relation-input-hint-missing"),
        severity: Severity::Warning,
        source: "elab",
        kind: Kind::Warning,
        state: State::Pending,
        primary: Some(Location {
            file: "relation-no-input-hint.watsup",
            start: (3, 0),
            end: Some((3, 23)),
        }),
        obligations: "Operation succeeds while collecting this warning; do not demand a fatal failure.",
    },
    Case {
        name: "rule-multiple-otherwise-rules.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/rule-multiple-otherwise"),
        code: Some("elab/rule-group-otherwise-rule-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "rule-multiple-otherwise-rules.watsup",
            start: (10, 2),
            end: Some((12, 16)),
        }),
        obligations: "Secondary: rule-multiple-otherwise-rules.watsup:7:2..9:16 first `otherwise` rule here",
    },
    Case {
        name: "rule-other-rule-before-otherwise.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/rule-otherwise-with-other-rule"),
        code: Some("elab/rule-group-otherwise-rule-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "rule-other-rule-before-otherwise.watsup",
            start: (9, 2),
            end: Some((11, 16)),
        }),
        obligations: "Secondary: rule-other-rule-before-otherwise.watsup:7:2..8:10 other rule here",
    },
    Case {
        name: "rule-relation-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/rule-relation-mismatch"),
        code: Some("elab/rule-group-relation-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "rule-relation-mismatch.watsup",
            start: (11, 7),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: rule-relation-mismatch.watsup:9:10 (verify endpoint at source site) enclosing rule group names relation `R`",
    },
    Case {
        name: "table-function-parameter.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-function-parameter"),
        code: Some("elab/table-parameter-kind-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-function-parameter.watsup",
            start: (1, 16),
            end: Some((1, 30)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "table-missing-rows.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-missing-rows"),
        code: Some("elab/table-row-missing"),
        severity: Severity::Warning,
        source: "elab",
        kind: Kind::Warning,
        state: State::Pending,
        primary: Some(Location {
            file: "table-missing-rows.watsup",
            start: (1, 0),
            end: Some((1, 27)),
        }),
        obligations: "Operation succeeds while collecting this warning; do not demand a fatal failure.",
    },
    Case {
        name: "table-non-bool-return.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/table-non-bool-return"),
        code: Some("elab/table-return-type-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-non-bool-return.watsup",
            start: (7, 23),
            end: Some((7, 26)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-call-arg-arity-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/call-arg-arity-mismatch"),
        code: Some("elab/function-argument-arity-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-call-arg-arity-mismatch.watsup",
            start: (6, 9),
            end: Some((6, 14)),
        }),
        obligations: "Secondary: type-call-arg-arity-mismatch.watsup:3:5..3:7 function declared here",
    },
    Case {
        name: "type-call-targ-arity-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/call-targ-arity-mismatch"),
        code: Some("elab/function-type-argument-arity-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-call-targ-arity-mismatch.watsup",
            start: (6, 17),
            end: Some((6, 20)),
        }),
        obligations: "Secondary: type-call-targ-arity-mismatch.watsup:3:5..3:7 declared here",
    },
    Case {
        name: "type-clause-arg-arity-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/clause-arg-arity-mismatch"),
        code: Some("elab/function-clause-argument-arity-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-clause-arg-arity-mismatch.watsup",
            start: (4, 10),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: type-clause-arg-arity-mismatch.watsup:3:5..3:7 declared here",
    },
    Case {
        name: "type-clause-tparam-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/clause-tparam-mismatch"),
        code: Some("elab/function-clause-type-parameter-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-clause-tparam-mismatch.watsup",
            start: (4, 7),
            end: Some((4, 11)),
        }),
        obligations: "Secondary: type-clause-tparam-mismatch.watsup:3:7 (verify endpoint at source site) expected type parameters declared here",
    },
    Case {
        name: "type-dec-missing-clauses.watsup",
        suite: Suite::Elab,
        owner: "D03",
        reference_code: Some("elab/dec-missing-clauses"),
        code: Some("elab/function-clause-missing"),
        severity: Severity::Warning,
        source: "elab",
        kind: Kind::Warning,
        state: State::Pending,
        primary: Some(Location {
            file: "type-dec-missing-clauses.watsup",
            start: (1, 0),
            end: Some((1, 18)),
        }),
        obligations: "Operation succeeds while collecting this warning; do not demand a fatal failure.",
    },
    Case {
        name: "type-define-extern.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/typ-define-extern"),
        code: Some("elab/extern-type-definition-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-define-extern.watsup",
            start: (2, 7),
            end: Some((2, 13)),
        }),
        obligations: "Secondary: type-define-extern.watsup:1:14..1:20 extern type declared here",
    },
    Case {
        name: "type-extend-extern.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/extend-non-variant-extern"),
        code: Some("elab/extern-type-extension-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-extend-extern.watsup",
            start: (4, 4),
            end: Some((4, 10)),
        }),
        obligations: "Secondary: type-extend-extern.watsup:1:14..1:20 extern type declared here",
    },
    Case {
        name: "type-extend-forward-decl.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/extend-incomplete"),
        code: Some("elab/type-extension-incomplete"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-extend-forward-decl.watsup",
            start: (7, 4),
            end: Some((7, 14)),
        }),
        obligations: "Secondary: type-extend-forward-decl.watsup:4:7..4:17 originally declared here",
    },
    Case {
        name: "type-extend-param.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/extend-non-variant-tparam"),
        code: Some("elab/type-parameter-extension-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location { file: "type-extend-param.watsup", start: (2, 4), end: None }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: type-extend-param.watsup:1:15 (verify endpoint at source site) type parameter declared here",
    },
    Case {
        name: "type-extend-primitive.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/extend-non-variant-primitive"),
        code: Some("elab/primitive-type-extension-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-extend-primitive.watsup",
            start: (2, 4),
            end: Some((2, 8)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-extend-struct.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/extend-non-variant-struct"),
        code: Some("elab/struct-type-extension-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-extend-struct.watsup",
            start: (7, 4),
            end: Some((7, 12)),
        }),
        obligations: "Secondary: type-extend-struct.watsup:4:7..4:15 originally defined here",
    },
    Case {
        name: "type-forward-tparam-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/typ-tparam-mismatch"),
        code: Some("elab/type-definition-parameter-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-forward-tparam-mismatch.watsup",
            start: (5, 11),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: type-forward-tparam-mismatch.watsup:4:7..4:10 declaration with no type parameters here",
    },
    Case {
        name: "type-funarg-expected-exp-got-fun.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/funarg-expected-exp-got-fun"),
        code: Some("elab/function-argument-kind-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-funarg-expected-exp-got-fun.watsup",
            start: (9, 20),
            end: Some((9, 26)),
        }),
        obligations: "Secondary: type-funarg-expected-exp-got-fun.watsup:6:12..6:15 parameter declared here",
    },
    Case {
        name: "type-funarg-expected-fun-got-exp.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/funarg-expected-fun-got-exp"),
        code: Some("elab/function-argument-kind-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-funarg-expected-fun-got-exp.watsup",
            start: (8, 20),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: type-funarg-expected-fun-got-exp.watsup:4:12..4:29 parameter declared here",
    },
    Case {
        name: "type-funarg-name-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/funarg-name-mismatch"),
        code: Some("elab/function-argument-name-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-funarg-name-mismatch.watsup",
            start: (5, 17),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: type-funarg-name-mismatch.watsup:4:17..4:25 function parameter declared here",
    },
    Case {
        name: "type-funarg-signature-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/funarg-signature-mismatch"),
        code: Some("elab/function-argument-signature-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-funarg-signature-mismatch.watsup",
            start: (6, 20),
            end: Some((6, 26)),
        }),
        obligations: "Secondary: type-funarg-signature-mismatch.watsup:3:17..3:19 function parameter declared here Secondary: type-funarg-signature-mismatch.watsup:1:5..1:7 passed function declared here",
    },
    Case {
        name: "type-functyp-param-arity-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/functyp-param-arity-mismatch"),
        code: Some("elab/function-argument-parameter-arity-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-functyp-param-arity-mismatch.watsup",
            start: (8, 19),
            end: Some((8, 25)),
        }),
        obligations: "Secondary: type-functyp-param-arity-mismatch.watsup:5:17..5:19 function parameter declared here Secondary: type-functyp-param-arity-mismatch.watsup:4:5..4:7 passed function declared here",
    },
    Case {
        name: "type-functyp-tparam-arity-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D05",
        reference_code: Some("elab/functyp-tparam-arity-mismatch"),
        code: Some("elab/function-argument-type-parameter-arity-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-functyp-tparam-arity-mismatch.watsup",
            start: (8, 19),
            end: Some((8, 25)),
        }),
        obligations: "Secondary: type-functyp-tparam-arity-mismatch.watsup:5:17..5:19 function parameter declared here Secondary: type-functyp-tparam-arity-mismatch.watsup:4:5..4:7 passed function declared here",
    },
    Case {
        name: "type-fuse-outside-hint.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/fuse-outside-hint"),
        code: Some("elab/token-concatenation-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-fuse-outside-hint.watsup",
            start: (5, 11),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "type-hole-outside-hint.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/hole-outside-hint"),
        code: Some("elab/hint-hole-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-hole-outside-hint.watsup",
            start: (5, 9),
            end: Some((5, 11)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-latex-outside-hint.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/latex-outside-hint"),
        code: Some("elab/latex-literal-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-latex-outside-hint.watsup",
            start: (5, 9),
            end: Some((5, 24)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-missing-definition.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/typ-missing-definition"),
        code: Some("elab/type-definition-missing"),
        severity: Severity::Warning,
        source: "elab",
        kind: Kind::Warning,
        state: State::Pending,
        primary: Some(Location {
            file: "type-missing-definition.watsup",
            start: (1, 7),
            end: Some((1, 15)),
        }),
        obligations: "Operation succeeds while collecting this warning; do not demand a fatal failure.",
    },
    Case {
        name: "type-redeclared.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/type-redeclared"),
        code: Some("elab/type-declaration-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-redeclared.watsup",
            start: (2, 7),
            end: Some((2, 10)),
        }),
        obligations: "Secondary: type-redeclared.watsup:1:7..1:10 first declared here",
    },
    Case {
        name: "type-syn-invalid-id.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/syn-invalid-id"),
        code: Some("elab/type-identifier-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-syn-invalid-id.watsup",
            start: (4, 7),
            end: Some((4, 10)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-syn-tparam-duplicate.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/syn-tparam-not-distinct"),
        code: Some("elab/type-parameter-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-syn-tparam-duplicate.watsup",
            start: (1, 17),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: type-syn-tparam-duplicate.watsup:1:14 (verify endpoint at source site) first declared here",
    },
    Case {
        name: "type-typ-invalid-id.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/typ-invalid-id"),
        code: Some("elab/type-identifier-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-typ-invalid-id.watsup",
            start: (4, 7),
            end: Some((4, 10)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-typ-invalid-tparam.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/typ-invalid-tparam"),
        code: Some("elab/type-parameter-identifier-invalid"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-typ-invalid-tparam.watsup",
            start: (4, 11),
            end: Some((4, 14)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-undefined-syntax.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/type-undefined"),
        code: Some("elab/type-undefined"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-undefined-syntax.watsup",
            start: (3, 22),
            end: Some((3, 26)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-unparen-outside-hint.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/unparen-outside-hint"),
        code: Some("elab/unparenthesizing-operator-unsupported"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-unparen-outside-hint.watsup",
            start: (5, 9),
            end: Some((5, 11)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "type-variant-mixop-collision.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/variant-mixop-collision"),
        code: Some("elab/variant-case-shape-repeated"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-variant-mixop-collision.watsup",
            start: (6, 4),
            end: Some((6, 7)),
        }),
        obligations: "Secondary: type-variant-mixop-collision.watsup:5:4..5:7 earlier case with this shape",
    },
    Case {
        name: "type-vart-targ-arity-mismatch.watsup",
        suite: Suite::Elab,
        owner: "D04",
        reference_code: Some("elab/vart-targ-arity-mismatch"),
        code: Some("elab/type-argument-arity-mismatch"),
        severity: Severity::Error,
        source: "elab",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "type-vart-targ-arity-mismatch.watsup",
            start: (5, 13),
            end: Some((5, 16)),
        }),
        obligations: "Secondary: type-vart-targ-arity-mismatch.watsup:3:7..3:11 type declared here",
    },
    Case {
        name: "dataflow-bind-both-sides-of-equality.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/bind-both-sides-of-equality"),
        code: Some("algo/equality-binding-invalid"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "dataflow-bind-both-sides-of-equality.watsup",
            start: (14, 8),
            end: Some((14, 13)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "dataflow-bind-in-non-invertible.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/non-invertible-binding"),
        code: Some("algo/operator-binding-unsupported"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "dataflow-bind-in-non-invertible.watsup",
            start: (13, 9),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "dataflow-free-variable-in-output.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/free-variable-in-expression"),
        code: Some("algo/expression-variable-undefined"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "dataflow-free-variable-in-output.watsup",
            start: (14, 7),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "dataflow-iter-binding-only.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/iteration-missing-loop-variable"),
        code: Some("algo/iteration-variable-missing"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "dataflow-iter-binding-only.watsup",
            start: (13, 6),
            end: Some((13, 14)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "dataflow-parallel-binding-dimension-mismatch.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/parallel-binding-dimension-mismatch"),
        code: Some("algo/binding-iteration-dimension-mismatch"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "dataflow-parallel-binding-dimension-mismatch.watsup",
            start: (10, 7),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: dataflow-parallel-binding-dimension-mismatch.watsup:10:3 (verify endpoint at source site) first bound here",
    },
    Case {
        name: "function-otherwise-condition.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/condition-in-otherwise"),
        code: Some("algo/otherwise-condition-unsupported"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "function-otherwise-condition.watsup",
            start: (5, 5),
            end: Some((5, 12)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "function-otherwise-function-call.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/function-call-in-otherwise"),
        code: Some("algo/otherwise-function-call-unsupported"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "function-otherwise-function-call.watsup",
            start: (11, 17),
            end: Some((11, 29)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "function-otherwise-relation-call.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/relation-call-in-otherwise"),
        code: Some("algo/otherwise-relation-call-unsupported"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "function-otherwise-relation-call.watsup",
            start: (13, 5),
            end: Some((13, 14)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "table-non-shallow-binding.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/table-row-binding-shape"),
        code: Some("algo/table-binding-shape-invalid"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-non-shallow-binding.watsup",
            start: (4, 4),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "table-pattern-expected-named-variant.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/pattern-non-variant-type"),
        code: Some("algo/table-pattern-type-invalid"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-pattern-expected-named-variant.watsup",
            start: (1, 16),
            end: Some((1, 19)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "table-pattern-extern.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/pattern-non-variant-type"),
        code: Some("algo/table-pattern-type-invalid"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-pattern-extern.watsup",
            start: (3, 16),
            end: Some((3, 22)),
        }),
        obligations: "Secondary: table-pattern-extern.watsup:1:14..1:20 type declared here",
    },
    Case {
        name: "table-pattern-incomplete.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/pattern-incomplete"),
        code: Some("algo/table-pattern-incomplete"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-pattern-incomplete.watsup",
            start: (8, 13),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: table-pattern-incomplete.watsup:3:4 (verify endpoint at source site) case in uncovered pattern",
    },
    Case {
        name: "table-pattern-non-variant.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/pattern-non-variant-type"),
        code: Some("algo/table-pattern-type-invalid"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-pattern-non-variant.watsup",
            start: (3, 16),
            end: Some((3, 22)),
        }),
        obligations: "Secondary: table-pattern-non-variant.watsup:1:7..1:13 type declared here",
    },
    Case {
        name: "table-pattern-overlap.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/pattern-overlap"),
        code: Some("algo/table-pattern-overlapping"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location { file: "table-pattern-overlap.watsup", start: (9, 4), end: None }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: table-pattern-overlap.watsup:8:4 (verify endpoint at source site) earlier overlapping pattern",
    },
    Case {
        name: "table-repeated-binding.watsup",
        suite: Suite::Algo,
        owner: "D06",
        reference_code: Some("algo/repeated-table-binding"),
        code: Some("algo/table-binding-repeated"),
        severity: Severity::Error,
        source: "algo",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "table-repeated-binding.watsup",
            start: (11, 11),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width. Secondary: table-repeated-binding.watsup:11:8 (verify endpoint at source site) first bound here",
    },
    Case {
        name: "hint-prose-fields-arity.watsup",
        suite: Suite::Prose,
        owner: "D08",
        reference_code: Some("prose/hint-fields-arity-mismatch"),
        code: Some("prose/field-hint-arity-mismatch"),
        severity: Severity::Error,
        source: "prose",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "hint-prose-fields-arity.watsup",
            start: (2, 28),
            end: Some((2, 35)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "hint-prose-fields-shape.watsup",
        suite: Suite::Prose,
        owner: "D08",
        reference_code: Some("prose/hint-fields-text-expected"),
        code: Some("prose/field-hint-element-invalid"),
        severity: Severity::Error,
        source: "prose",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "hint-prose-fields-shape.watsup",
            start: (2, 20),
            end: None,
        }),
        obligations: "Verify primary endpoint at source site; a one-caret snapshot may be zero-width.",
    },
    Case {
        name: "hint-prose-index-out-of-range.watsup",
        suite: Suite::Prose,
        owner: "D08",
        reference_code: Some("prose/hint-placeholder-out-of-bounds"),
        code: Some("prose/hint-placeholder-out-of-bounds"),
        severity: Severity::Error,
        source: "prose",
        kind: Kind::Failure,
        state: State::Pending,
        primary: Some(Location {
            file: "hint-prose-index-out-of-range.watsup",
            start: (2, 16),
            end: Some((2, 18)),
        }),
        obligations: "Match the primary source range.",
    },
    Case {
        name: "interp-al-syntax-diagnostic",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: Some("parse/test"),
        code: Some("parse/test"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Preservation,
        state: State::Pending,
        primary: Some(Location { file: "", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Secondary: generated syntax related item Trace: generated syntax trace Return syntax failure identity unchanged, including all fields; successful preservation renders no diagnostic. Preserve detail Syntax detail. and generated regions without source invention.",
    },
    Case {
        name: "interp-sl-syntax-diagnostic",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: Some("parse/test"),
        code: Some("parse/test"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Preservation,
        state: State::Pending,
        primary: Some(Location { file: "", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Secondary: generated syntax related item Trace: generated syntax trace Return syntax failure identity unchanged, including all fields; successful preservation renders no diagnostic. Preserve detail Syntax detail. and generated regions without source invention.",
    },
    Case {
        name: "interp-pl-syntax-diagnostic",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: Some("parse/test"),
        code: Some("parse/test"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Preservation,
        state: State::Deferred("G15"),
        primary: Some(Location { file: "", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Secondary: generated syntax related item Trace: generated syntax trace Return syntax failure identity unchanged, including all fields; successful preservation renders no diagnostic. Preserve detail Syntax detail. and generated regions without source invention.",
    },
    Case {
        name: "interp-al-extern-diagnostic",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: Some("sim/test"),
        code: Some("sim/test"),
        severity: Severity::Error,
        source: "sim",
        kind: Kind::Preservation,
        state: State::Pending,
        primary: Some(Location { file: "", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Secondary: generated external related item Trace: generated external trace root -> [generated external trace leaf] Fatal Abort returns unchanged across extern boundary; successful preservation renders no diagnostic. Preserve detail external detail, code, source, generated related locations, nested trace order.",
    },
    Case {
        name: "interp-sl-extern-diagnostic",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: Some("sim/test"),
        code: Some("sim/test"),
        severity: Severity::Error,
        source: "sim",
        kind: Kind::Preservation,
        state: State::Pending,
        primary: Some(Location { file: "", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Secondary: generated external related item Trace: generated external trace root -> [generated external trace leaf] Fatal Abort returns unchanged across extern boundary; successful preservation renders no diagnostic. Preserve detail external detail, code, source, generated related locations, nested trace order.",
    },
    Case {
        name: "interp-pl-extern-diagnostic",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: Some("sim/test"),
        code: Some("sim/test"),
        severity: Severity::Error,
        source: "sim",
        kind: Kind::Preservation,
        state: State::Deferred("G15"),
        primary: Some(Location { file: "", start: (0, 0), end: Some((0, 0)) }),
        obligations: "Secondary: generated external related item Trace: generated external trace root -> [generated external trace leaf] Fatal Abort returns unchanged across extern boundary; successful preservation renders no diagnostic. Preserve detail external detail, code, source, generated related locations, nested trace order.",
    },
    Case {
        name: "interp-al-backtrack",
        suite: Suite::Interp,
        owner: "D09",
        reference_code: None,
        code: Some("runtime/relation-match-failed"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Failure,
        state: State::Pending,
        primary: None,
        obligations: "Trace: cases/interp/backtrack.watsup:7:2..7:3 Preserve ordered root/leaf trace and branch control; primary root remains unlocated as in reference. Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-sl-backtrack",
        suite: Suite::Interp,
        owner: "D09",
        reference_code: None,
        code: Some("runtime/relation-match-failed"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Failure,
        state: State::Pending,
        primary: None,
        obligations: "Trace: cases/interp/backtrack.watsup:7:2..7:3 Preserve ordered root/leaf trace and branch control; primary root remains unlocated as in reference. Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-pl-backtrack",
        suite: Suite::Interp,
        owner: "D09",
        reference_code: None,
        code: Some("runtime/relation-match-failed"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Failure,
        state: State::Deferred("G15"),
        primary: None,
        obligations: "Trace: cases/interp/backtrack.watsup:7:2..7:3 Preserve ordered root/leaf trace and branch control; primary root remains unlocated as in reference. Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-al-extern-failtraces",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: None,
        code: Some("runtime/relation-match-failed"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Preservation,
        state: State::Pending,
        primary: None,
        obligations: "Trace: cases/interp/external.watsup:15:5..15:28 Preserve recoverable Unmatch until execution boundary promotes exhausted alternatives. Retain nested external relation failed -> external leaf generated frames in order, plus exact preceding source-bearing frames from expected section. Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-sl-extern-failtraces",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: None,
        code: Some("runtime/relation-match-failed"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Preservation,
        state: State::Pending,
        primary: None,
        obligations: "Trace: cases/interp/external.watsup:15:5..15:28 Preserve recoverable Unmatch until execution boundary promotes exhausted alternatives. Retain nested external relation failed -> external leaf generated frames in order, plus exact preceding source-bearing frames from expected section. Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-pl-extern-failtraces",
        suite: Suite::Interp,
        owner: "D10",
        reference_code: None,
        code: Some("runtime/relation-match-failed"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Preservation,
        state: State::Deferred("G15"),
        primary: None,
        obligations: "Trace: cases/interp/external.watsup:13:6..13:13 Trace: cases/interp/external.watsup:15:5..15:36 Trace: cases/interp/external.watsup:15:5..15:28 Preserve recoverable Unmatch until execution boundary promotes exhausted alternatives. Retain nested external relation failed -> external leaf generated frames in order, plus exact preceding source-bearing frames from expected section. Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "command-error",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: None,
        code: None,
        severity: Severity::Error,
        source: "command",
        kind: Kind::Failure,
        state: State::Pending,
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "command-boot-source-conflict",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("command/boot-source-conflict"),
        code: Some("command/boot-source-invalid"),
        severity: Severity::Error,
        source: "command",
        kind: Kind::Failure,
        state: State::Deferred("G20/G21"),
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "command-boot-source-required",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("command/boot-source-required"),
        code: Some("command/boot-source-missing"),
        severity: Severity::Error,
        source: "command",
        kind: Kind::Failure,
        state: State::Deferred("G20/G21"),
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "command-splice-file-count-mismatch",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("command/splice-file-count-mismatch"),
        code: Some("command/splice-file-count-mismatch"),
        severity: Severity::Error,
        source: "command",
        kind: Kind::Failure,
        state: State::Deferred("G19/G21"),
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "boot-unsupported-interface",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("boot/unsupported-interface"),
        code: Some("command/boot-interface-unsupported"),
        severity: Severity::Error,
        source: "command",
        kind: Kind::Failure,
        state: State::Deferred("G20"),
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-al-duplicate-type",
        suite: Suite::Boundary,
        owner: "D09",
        reference_code: None,
        code: Some("runtime/type-repeated"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Failure,
        state: State::Pending,
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-sl-duplicate-type",
        suite: Suite::Boundary,
        owner: "D09",
        reference_code: None,
        code: Some("runtime/type-repeated"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Failure,
        state: State::Pending,
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "interp-pl-duplicate-type",
        suite: Suite::Boundary,
        owner: "D09",
        reference_code: None,
        code: Some("runtime/type-repeated"),
        severity: Severity::Error,
        source: "runtime",
        kind: Kind::Failure,
        state: State::Deferred("G15"),
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
    Case {
        name: "parse-al-diagnostic",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("parse/hint-on-plain-type"),
        code: Some("parse/plain-type-hint-unsupported"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Preservation,
        state: State::Deferred("G20"),
        primary: Some(Location { file: "input.watsup", start: (1, 19), end: Some((1, 29)) }),
        obligations: "Compare all diagnostic fields with generic SpecTec parser result for identical input; preserve source code/producer already assigned by parser. Source input: syntax foo = | nat hint(blah). Successful equality renders no diagnostic.",
    },
    Case {
        name: "parse-sl-diagnostic",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("parse/hint-on-plain-type"),
        code: Some("parse/plain-type-hint-unsupported"),
        severity: Severity::Error,
        source: "parse",
        kind: Kind::Preservation,
        state: State::Deferred("G20"),
        primary: Some(Location { file: "input.watsup", start: (1, 19), end: Some((1, 29)) }),
        obligations: "Compare all diagnostic fields with generic SpecTec parser result for identical input; preserve source code/producer already assigned by parser. Source input: syntax foo = | nat hint(blah). Successful equality renders no diagnostic.",
    },
    Case {
        name: "sim-unsupported-architecture",
        suite: Suite::Boundary,
        owner: "D10",
        reference_code: Some("sim/unsupported-architecture"),
        code: Some("sim/architecture-unsupported"),
        severity: Severity::Error,
        source: "sim",
        kind: Kind::Failure,
        state: State::Pending,
        primary: None,
        obligations: "Reference root has no region; do not invent a source location.",
    },
];
