//! Diagnostics for partial operations in otherwise bodies
//!
//! Callers locate the first forbidden premise or nested function call.

use super::{AlgoError, cause};
use crate::{
    diagnostic::Label,
    lang::{
        common::{Id, source::Span},
        il::ast::Otherwise,
        traits::at::At,
    },
    pass::algo::binding::partial::ConditionOrigin,
};

const OTHERWISE_CONDITION_INVALID: &str = "algo/otherwise-condition-invalid";
const OTHERWISE_PATTERN_CONDITION_INVALID: &str = "algo/otherwise-pattern-condition-invalid";

/// Reports a conditional premise in an otherwise body.
pub(crate) fn otherwise_condition_invalid(span: &Span, otherwise: &Otherwise) -> AlgoError {
    cause(
        OTHERWISE_CONDITION_INVALID,
        "an `otherwise` body cannot test a condition",
        vec![
            Label::primary(span, ""),
            Label::secondary(&otherwise.at(), "`otherwise` body starts here"),
        ],
        vec![],
    )
}

/// Explains the equality generated by a repeated binder in a fallback pattern.
pub(crate) fn otherwise_repeated_pattern_invalid(
    id_bound: &Id,
    id_repeated: &Id,
    otherwise: &Otherwise,
) -> AlgoError {
    cause(
        OTHERWISE_PATTERN_CONDITION_INVALID,
        format!(
            "repeating `{}` requires an equality check, which is not allowed in an `otherwise` clause",
            id_repeated.node
        ),
        vec![
            Label::primary(&id_repeated.span, format!("repeated `{}`", id_repeated.node)),
            Label::secondary(&id_bound.span, "first bound here"),
            Label::secondary(&otherwise.at(), "`otherwise` clause starts here"),
        ],
        vec![],
    )
}

/// Explains a condition introduced while rewriting a fallback pattern.
pub(crate) fn otherwise_pattern_condition_invalid(
    origin: &ConditionOrigin,
    otherwise: &Otherwise,
) -> AlgoError {
    let (span, message) = match origin {
        // Compare a bound sub-pattern with its source value
        ConditionOrigin::Equality(span) => {
            (span, "this pattern requires an equality check".to_owned())
        }
        // Match an injected or non-singleton shape
        ConditionOrigin::Match(span, construct) => {
            (span, format!("matching this {construct} requires a check"))
        }
        // Check that the source belongs to the subtype
        ConditionOrigin::Subtype(span) => {
            (span, "this pattern requires a subtype check".to_owned())
        }
    };
    cause(
        OTHERWISE_PATTERN_CONDITION_INVALID,
        format!("{message}, which is not allowed in an `otherwise` clause"),
        vec![
            Label::primary(span, "pattern requiring a condition"),
            Label::secondary(&otherwise.at(), "`otherwise` clause starts here"),
        ],
        vec![],
    )
}

const OTHERWISE_FUNCTION_CALL_INVALID: &str = "algo/otherwise-function-call-invalid";

/// Reports the nested function call in an otherwise body.
pub(crate) fn otherwise_function_call_invalid(span: &Span, otherwise: &Otherwise) -> AlgoError {
    cause(
        OTHERWISE_FUNCTION_CALL_INVALID,
        "an `otherwise` body cannot call a function",
        vec![
            Label::primary(span, ""),
            Label::secondary(&otherwise.at(), "`otherwise` body starts here"),
        ],
        vec![],
    )
}

const OTHERWISE_RELATION_CALL_INVALID: &str = "algo/otherwise-relation-call-invalid";

/// Reports a relation call in an otherwise body.
pub(crate) fn otherwise_relation_call_invalid(span: &Span, otherwise: &Otherwise) -> AlgoError {
    cause(
        OTHERWISE_RELATION_CALL_INVALID,
        "an `otherwise` body cannot call a relation",
        vec![
            Label::primary(span, ""),
            Label::secondary(&otherwise.at(), "`otherwise` body starts here"),
        ],
        vec![],
    )
}
