//! Codecs for the JSON representation generated by `ppx_deriving_yojson`

pub mod atom;
pub mod lang;
pub mod mixfix;
pub mod source;

use serde_json::{Map, Value};
use thiserror::Error;

#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum DecodeError {
    #[error("expected {0}")]
    Expected(&'static str),

    #[error("missing field `{0}`")]
    MissingField(&'static str),

    #[error("unknown OCaml variant `{0}`")]
    UnknownVariant(String),
}

#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum EncodeError {
    #[error("unsupported external JSON data: {0}")]
    UnsupportedExternalData(String),
}

const CODEC_STACK_SIZE: usize = 32 * 1024 * 1024;

pub(crate) fn on_codec_stack<T>(codec: impl FnOnce() -> T) -> T {
    stacker::grow(CODEC_STACK_SIZE, codec)
}

pub(crate) fn array(value: &Value) -> Result<&[Value], DecodeError> {
    value
        .as_array()
        .map(Vec::as_slice)
        .ok_or(DecodeError::Expected("array"))
}

pub(crate) fn string(value: &Value) -> Result<&str, DecodeError> {
    value.as_str().ok_or(DecodeError::Expected("string"))
}

pub(crate) fn boolean(value: &Value) -> Result<bool, DecodeError> {
    value.as_bool().ok_or(DecodeError::Expected("boolean"))
}

pub(crate) fn integer(value: &Value) -> Result<i64, DecodeError> {
    value.as_i64().ok_or(DecodeError::Expected("integer"))
}

pub(crate) fn object(value: &Value) -> Result<&Map<String, Value>, DecodeError> {
    value.as_object().ok_or(DecodeError::Expected("object"))
}

pub(crate) fn field<'a>(
    object: &'a Map<String, Value>,
    name: &'static str,
) -> Result<&'a Value, DecodeError> {
    object.get(name).ok_or(DecodeError::MissingField(name))
}

pub(crate) fn variant(value: &Value) -> Result<(&str, &[Value]), DecodeError> {
    let values = array(value)?;
    let (tag, fields) = values
        .split_first()
        .ok_or(DecodeError::Expected("non-empty variant array"))?;
    Ok((string(tag)?, fields))
}
