//! Codecs for the JSON representation generated by `ppx_deriving_yojson`

pub mod atom;
pub mod mixfix;
pub mod source;

use serde_json::Value;
use thiserror::Error;

#[derive(Clone, Debug, Error, PartialEq, Eq)]
pub enum DecodeError {
    #[error("expected {0}")]
    Expected(&'static str),

    #[error("missing field `{0}`")]
    MissingField(&'static str),

    #[error("unknown OCaml variant `{0}`")]
    UnknownVariant(String),
}

pub(crate) fn array(value: &Value) -> Result<&[Value], DecodeError> {
    value
        .as_array()
        .map(Vec::as_slice)
        .ok_or(DecodeError::Expected("array"))
}

pub(crate) fn string(value: &Value) -> Result<&str, DecodeError> {
    value.as_str().ok_or(DecodeError::Expected("string"))
}

pub(crate) fn variant(value: &Value) -> Result<(&str, &[Value]), DecodeError> {
    let values = array(value)?;
    let (tag, fields) = values
        .split_first()
        .ok_or(DecodeError::Expected("non-empty variant array"))?;
    Ok((string(tag)?, fields))
}
