[package]
name = "p4spec-rust"
version = "0.1.0"
edition = "2024"
rust-version = "1.97.1"

[dependencies]
imbl = { version = "7.0.1", default-features = false }
lalrpop-util = { version = "0.23.1", default-features = false }
num-bigint = "0.4.6"
num-traits = "0.2.19"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128", features = ["unbounded_depth"] }
serde_stacker = "0.1.11"
stacker = "0.1.25"
thiserror = "1.0.63"

[build-dependencies]
lalrpop = { version = "0.23.1", default-features = false }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = "warn"
